/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.training.todoapp.controller;

import com.training.todoapp.entity.Todo;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-08-30T16:52:58.636913200+07:00[Asia/Saigon]")
@Validated
@Tag(name = "todos", description = "the todos API")
public interface TodosApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /todos : Get all todos
     *
     * @return A list of todos (status code 200)
     */
    @Operation(
        operationId = "todosGet",
        summary = "Get all todos",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of todos")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/todos"
    )
    default ResponseEntity<Void> todosGet(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /todos : Create a new todo
     *
     * @param todo  (optional)
     * @return Created todo (status code 201)
     */
    @Operation(
        operationId = "todosPost",
        summary = "Create a new todo",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created todo")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/todos",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> todosPost(
        @Parameter(name = "Todo", description = "", schema = @Schema(description = "")) @Valid @RequestBody(required = false) Todo todo
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
