openapi: 3.0.1
info:
  title: ToDoApp API
  description: API for managing ToDo items
  version: 1.0.0

paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        200:
          description: A list of todos
    post:
      summary: Create a new todo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        201:
          description: Created todo

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean