spring:
  datasource:
    url: jdbc:oracle:thin:@66.66.66.13:1521/ORCLPDB1
    username: duc1807
    password: 1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

server:
  port: 8080